import React, { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { requestGQL } from '../gql/client';
import { getCountries } from '../gql/queries/countryQuerys'
import { Countries, Filters } from '../components';
const Home = ({ data }) => {
  const [countries, setCountries] = useState(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Por favor seleccione el pais preferido
        </h1>
        <Filters countries={data} setCountries={setCountries} />
        <Countries countries={countries} />
      </main>

      <footer className={styles.footer}>
        <h2>
          <a href="/tickets">
            Ejercicio de Tickets
          </a>
        </h2>

      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const { data } = await requestGQL(getCountries).then(data => data)
  return { props: { data: data.countries } }
}

export default Home